OBJS = history.o tokenizer.o uimain.o
CFLAGS = -g -03

all: tokenizer

tokenizer: $(OBJS)
	cc -o tokenizer $(CFLAGS) $(OBJS)

$(OBJS): history.h tokenizer.h

clean: rm -f *.o tokenizer

run: tokenizer
	./tokenizer
